name: Build and Push

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  IMAGE_NAME: juanfernandez250/babygenai

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .

    - name: Security scan with Docker Scout
      uses: docker/scout-action@v1
      with:
        command: cves
        image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
        only-severities: critical
        exit-code: true

    - name: Push to Docker Hub
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push ${{ env.IMAGE_NAME }}:latest